### ISSUE TITLE
Error: attempt to replicate an object of type 'closure' - when trying to replicate your examples

### ISSUE THREAD

**Issue by fraba** [sctyner/ggnet#1]
Hi,
Running R version 3.2.0 (2015-04-16) on x86_64-apple-darwin13.4.0

**Comment by sctyner** [comment]
Hi, I'm aware of this issue! I haven't quite figured it out yet. Plus there's a lot of higher level stuff I want to accomplish, too!  Thank you so much for your input and taking the time to play around with it!

**Comment by sctyner** [comment]
Hi again! I have resolved the issue! Could you please try the example again to make sure I've gotten it taken care of? 

Thanks!
