### ISSUE TITLE
Failed to install geomnet

### ISSUE THREAD

**Issue by hhsieh** [sctyner/ggnet#11]
Hi,

Thank you for creating this amazing product. I am eager to use it to generate network for my analysis. However, I am stuck at step one - I cannot install the package!! Here is the error message. Could you help me identify what the problem would be? Thank you!!

Downloading github repo sctyner/geomnet@master
Installing geomnet
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/0p/zrfyxxm9021bpfhlybcss75c0000gn/T/Rtmp4Nxf8o/devtoolsfee77a0000a/sctyner-geomnet-b78193e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
  --install-tests 
- installing _source_ package ‘geomnet’ ...
  *\* R
  *\* data
  **\* moving datasets to lazyload DB
  *\* preparing package for lazy loading
  Error : package ‘ggplot2’ 1.0.1 was found, but >= 1.0.1.9003 is required by ‘geomnet’
  ERROR: lazy loading failed for package ‘geomnet’
- removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/geomnet’
  Error: Command failed (1)

**Comment by esovik** [comment]
Install newest version of ggplot2 and try again.

**Comment by sctyner** [comment]
Thanks, @esovik. That's the solution. :100:
