### ISSUE TITLE
Change size of node labels

### ISSUE THREAD

**Issue by mjg4243** [sctyner/ggnet#12]
Maybe this can be done in ggplot2 but to date I can't figure out how.  I notice you provide for "labelcolour" in geom_net though.  My goal is to generate an even better network plot by making it more readable.  Also want to try to integrate "ggrepel."  As a teacher myself I really like being able to show students how to produce nice networks without a lot of messing around.  You have done a great job with "geomnet."

Best regards

Mike Gallagher

**Comment by sctyner** [comment]
Hi Mike. Thanks for the comment. This is actually available already -- it's just missing from the documentation. I've updated the documentation on github, and I will update the documentation in the next release to CRAN.  The option you're looking for is `fontsize =` in the `geom_net()` argument. Thanks again. :)

**Comment by mjg4243** [comment]
Thanks!  And thanks for responding so promptly.  Works great.
Best regards Mike Gallagher

```
  From: Samantha Tyner <notifications@github.com>
```

 To: sctyner/geomnet geomnet@noreply.github.com 
Cc: mjg4243 mjgallagher43@yahoo.com
 Sent: Monday, January 11, 2016 10:52 AM
 Subject: Re: [geomnet] Change size of node labels (#12)

Hi Mike. Thanks for the comment. This is actually available already -- it's just missing from the documentation. I've updated the documentation on github, and I will update the documentation in the next release to CRAN. The option you're looking for is fontsize = in the geom_net() argument. Thanks again. :) —

**Comment by mjg4243** [comment]
URGENT PLEASE CIRCULATE 
In the coming days, DO NOT open any message regardless of who sent it to you with an attachment called: BLACK MUSLIM IN THE WHITE HOUSE. It is a virus that opens an Olympics torch that burns the whole hard disk of your computer. 
  
Directions: You should send this message to all of your contacts. It is better to receive this e-mail 2 dozen times than to receive the virus and open it. 
  
If you receive a message called BLACK MUSLIM IN THE WHITE HOUSE even if sent by a friend, do not open and shut down your machine immediately. 
  
It is the worst virus ever announced by CNN. It has been classified by Microsoft as the most destructive virus ever. This virus was discovered yesterday afternoon by McAfee. There is no repair yet for this kind of virus. This virus destroys the Zero Sector of your hard disk, where vital information function is stored. 
  
Verified by snopes.com

Sent from my iPhone

 

|
|
|
|

 |
|  |

|
|
- 
- 
- 
- 
- 
- 
  |
  | 
  |
  |  |

Brighten your day. Mike Gallagher
