### ISSUE TITLE
Linewidth doesn't respond when inside aes()

### ISSUE THREAD

**Issue by drolejoel** [sctyner/ggnet#13]
linewidth argument is not responsive to values but only when mapped using aes()

```
library(ggplot2)
library(geomnet)

data("bikes")
# merge into a single data.frame()
bikes_merged <- merge(bikes$trips, bikes$stations, by.x="Start.station", by.y="name", all=TRUE)
# create a factor
bikes_merged$nbDocksfac <- as.factor(bikes_merged$nbDocks)

p <- ggplot(data = bikes_merged, aes(from_id = Start.station, to_id = End.station))

p + geom_net(aes(shape = nbDocksfac), colour = "blue", size = 6, linewidth=0.75, directed = TRUE, curvature=0.3)   # shapes are OK

p + geom_net(aes(colour = nbDocks), size = 6, directed = TRUE, curvature=0.3) # gradient colored nodes are OK

p + geom_net(aes(colour = nbDocksfac), size = 6, directed = TRUE, curvature=0.3) # categorical colored nodes are OK

p + geom_net(aes(size = nbDocksfac, colour = nbDocksfac),  directed = TRUE, curvature=0.3) # diff size & colour are OK

p + geom_net(aes(linetype = nbDocksfac), colour = "blue", size = 6, directed = TRUE, curvature=0.3) # linetypes are OK

p + geom_net(aes(linewidth = 2), colour = "blue", size = 6, directed = TRUE, curvature=0.3) # fixed linewidth inside aes() is OK

p + geom_net(colour = "blue", size = 6, linewidth = 2, directed = TRUE, curvature=0.3) # fixed linewidth is OK

p + geom_net(aes(linewidth = 0.99), colour = "blue", size = 6, directed = TRUE, curvature=0.3) # bug? linewidth not responsive
```

**Comment by briatte** [comment]
I think this is how `aes` is supposed to work: you are not supposed to pass straight values like 0.99 when  mapping your aesthetics; if you pass `"red"` to, say `colour`, inside `aes`, what you get is a factor with the single value `"red"`, not the colour `"red"`.

Also, I'm not sure what version of `ggplot2` you are using: your example does not work on my end. It seems the `bikes` dataset is different on your side than on mine. I'm on version 2.0.0 and the `as.factor` line of your code does not work.

Last, there's still an actual bug here:

``` R
library(ggplot2)
library(geomnet)

data("bikes")
bikes_merged <- merge(bikes$trips, bikes$stations, by.x="Start.station", by.y="name", all=TRUE)
p <- ggplot(data = bikes_merged, aes(from_id = Start.station, to_id = End.station))
p + geom_net(aes(linewidth = 0.99), colour = "blue", size = 6, directed = TRUE, curvature=0.3)
```

This returns:

```
Error in f(...) : could not find function "%>%"
```

If I load `magrittr`, I then get this instead:

```
Error in function_list[[i]](value) : could not find function "group_by"
```

… so it seems that `geomnet` is dependent on `dplyr`, which should load `magrittr`. The `dplyr` package should be moved from `Suggests` to `Imports` in the DESCRIPTION file.

**Comment by hrbrmstr** [comment]
Aye. `size=` within `aes()` == a factor level (in this case). `aes()` is for mapping colors, not direct specification of color values. posting output of `sessionInfo()` would help debug.

**Comment by drolejoel** [comment]
This is what I want to achieve with geomnet:  in order to show the _extent_ of transfer from node A to node B, I want to be able to draw lines between nodes with different thicknesses, based on the data in the data.frame, analogous to this is ggplot:  

```
library(ggplot2)
library(geomnet)
ggplot(mtcars, aes(wt, mpg, color = factor(cyl))) + geom_line(aes(size = factor(cyl)))
```

Nevertheless, in trying to explain myself better, I figured out what the problem was.  Here is my modified toy code.  As you can see, the line thickness can be changed.  No bug, after all.  :-)

```
bikes_merged <- merge(bikes$trips, bikes$stations, by.x="Start.station", by.y="name", all=TRUE)
bikes_merged$thickness <- sample( c(0.5, 1, 1.5), nrow(bikes_merged), replace = TRUE)

bikes_merged %<>% 
   arrange(Start.station, End.station) %>% 
   slice(5:15)

p <- ggplot(data = bikes_merged, aes(from_id = Start.station, to_id = End.station))

p + geom_net(aes(linewidth = thickness), colour = "blue", size = 6, directed = TRUE, curvature=0.3) 
```

> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: i386-w64-mingw32/i386 (32-bit)
> Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C  
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] network_1.13.0       sna_2.3-2            geomnet_0.0.1  
 [4] shinydashboard_0.5.1 shiny_0.13.0         dplyr_0.4.3  
 [7] magrittr_1.5         plyr_1.8.3           lubridate_1.5.0  
[10] readr_0.2.2          readxl_0.1.0         stringr_1.0.0  
[13] tidyr_0.4.0          httr_1.1.0           ggplot2_2.0.0       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3        munsell_0.4.2      colorspace_1.2-6  
 [4] xtable_1.8-0       R6_2.1.2           tools_3.2.2  
 [7] parallel_3.2.2     grid_3.2.2         gtable_0.1.2  
[10] DBI_0.3.1          htmltools_0.3      lazyeval_0.1.10  
[13] assertthat_0.1     digest_0.6.9       RColorBrewer_1.1-2
[16] mime_0.4           labeling_0.3       stringi_1.0-1  
[19] scales_0.3.0       httpuv_1.3.3
