### ISSUE TITLE
Not on CRAN

### ISSUE THREAD

**Issue by r-barnes** [sctyner/ggnet#27]
geomnet's no longer on CRAN. I wonder if you plan to get it back, or if you need help doing so?

**Comment by sctyner** [comment]
Hi, thanks for your note. Eventually, I do hope to get it back on CRAN. Right now, I'm waiting on the new version of [dplyr](https://www.tidyverse.org/blog/2020/04/dplyr-1-0-0-and-vctrs/) to be released before I start working on it. The current github version should work for now. If it's not, let me know. Thanks.

**Comment by r-barnes** [comment]
Thanks, @sctyner. It's somewhat problematic in the short term since I think `geomnet` is a dependency of `ggnetwork`.

**Comment by sctyner** [comment]
Hmm. That doesn't [appear](https://github.com/briatte/ggnetwork/blob/master/DESCRIPTION) to be true. You may be encountering an issue with [ggnetwork](https://github.com/briatte/ggnetwork/issues) itself? Sorry I can't be of more help right now.

**Comment by sctyner** [comment]
https://cran.r-project.org/web/packages/geomnet/index.html
