### ISSUE TITLE
students$Group <- ifelse(students$Marks>200 & students$Gender=="Male", 'A',                           ifelse(students$Marks >200 & students$Gender=="Female","B",                                 ifelse(students$Marks<=200 & students$Gender=="Male","C",                                        ifelse(students$Marks<=200 & students$Gender=="Female",D))))

### ISSUE THREAD

**Issue by rahulrvz** [sctyner/ggnet#28]
Error in rep(yes, length.out = len) : 
  attempt to replicate an object of type 'closure'

how i am suppose to deal with it

**Comment by sctyner** [comment]
This does not seem to be an issue with `geomnet`. Your issue name and description don't contain any calls to `geomnet` functions. I am closing this issue.
