### ISSUE TITLE
Strange dots in vertices when plotting to anything but .pdf

### ISSUE THREAD

**Issue by esovik** [sctyner/ggnet#9]
Vertices have strange dots when plotted as .jpg or .png (see below), but not when plotted as .pdf.

![jpgexample](https://cloud.githubusercontent.com/assets/972827/11380249/88e7e0fc-92ba-11e5-99f6-8d78d65bdc50.jpeg)
![pngexample](https://cloud.githubusercontent.com/assets/972827/11380250/88efe720-92ba-11e5-8504-41fd7a255470.png)
[PDFexample.pdf](https://github.com/sctyner/geomnet/files/43200/PDFexample.pdf)

**Comment by sctyner** [comment]
Could you provide information about the system you're using as well as some reproducible code? (https://github.com/textmate/textmate/wiki/Writing-Bug-Reports)

Thanks.

**Comment by esovik** [comment]
Yes, sorry. My bad. Here goes.

## System information:

R: 3.2.2
ggplot2: 10.0.1.90
geom_net: 0.0.1
OS X: 10.11.1 , happens both inside and outside Studio

## Reproducible example:

``` r
require(ggplot2)
require(geomnet)
require(magrittr)
require(dplyr)

Network <- data.frame(From = c(1,2,3,2,1),
                      To = c(2,3,1,3,2),
                      Size = c(3,4,5,0,0),
                      NodeSize = c(1,2,3,4,5))

p <- ggplot(Network, aes(from_id = From, to_id = To, linewidth = Size, size = NodeSize)) +
  geom_net(layout = "circle", ealpha = 0.4, ecolour = "black", curvature = 0.1) +
  theme_net()

png("pngExample.png", width = 1000, height = 1000); p; dev.off()
jpeg("jpgExample.jpg", width = 1000, height = 1000); p; dev.off()
pdf("pdfExample.pdf", width = 10, height = 10); p; dev.off()
```

Reducing curvature to 0 or reducing the size of the .jpg/.png below a certain threshold (differs between png/jpg) will remove the dots. Dots never appear in .pdf's regardless of size.

**Comment by briatte** [comment]
It looks like the vertices have their labels printed on top of them. The "strange" bits look like numbers.

I could not reproduce the issue: I get exactly the same graph regardless of format.

![pngexample](https://cloud.githubusercontent.com/assets/322533/11383612/c4f0950e-9309-11e5-9d4c-75707cb3fe26.png)

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sna_2.3-2          network_1.13.0     dplyr_0.4.3        magrittr_1.5       geomnet_0.0.1      ggplot2_1.0.1.9003

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2      digest_0.6.8     assertthat_0.1   grid_3.2.2       plyr_1.8.3       R6_2.1.1        
 [7] gtable_0.1.2     DBI_0.3.1        scales_0.3.0     lazyeval_0.1.10  labeling_0.3     tools_3.2.2     
[13] munsell_0.4.2    parallel_3.2.2   colorspace_1.2-6
```

**Comment by esovik** [comment]
Are we talking about the round dots 2/3 down the way of the lines? They do appear in the .png you attached. Did they also appear in the pdf?

``` r
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.1 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sna_2.3-2          network_1.13.0     dplyr_0.4.3        magrittr_1.5      
[5] geomnet_0.0.1      gridExtra_2.0.0    ggplot2_1.0.1.9003 devtools_1.9.1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1      digest_0.6.8     assertthat_0.1   R6_2.1.1        
 [5] grid_3.2.2       plyr_1.8.3       gtable_0.1.2     DBI_0.3.1       
 [9] scales_0.3.0     lazyeval_0.1.10  labeling_0.3     tools_3.2.2     
[13] munsell_0.4.2    parallel_3.2.2   colorspace_1.2-6 memoise_0.2.1 
```

**Comment by briatte** [comment]
Arg, you're right: I missed that (was looking just at the vertices). There is indeed a difference.

Do you also get them with `curvature = 0`? I don't.

**Comment by esovik** [comment]
No, I only get them when there is curvature.

**Comment by esovik** [comment]
Looks like the error is not unique to geom_net. I'm able to reproduce it using ggnetwork as well. Perhaps I should move this to another repository? Might be a ggplot2 issue rather than geom_net/ggnetwork.

``` r
require(ggplot2)
require(ggnetwork)
require(network)
require(sna)

Network <- network(rgraph(4, tprob = 0.2), directed = FALSE)
set.edge.attribute(Network, "Size", c(2,3,5))


p <- ggplot(ggnetwork(Network), aes(x = x, y = y, xend = xend, yend = yend)) + 
  geom_edges(aes(size = Size), curvature = 0.2, alpha = 0.4) + 
  theme_blank()

png("pngExample.png", width = 1000, height = 1000); p; dev.off()
jpeg("jpgExample.jpg", width = 1000, height = 1000); p; dev.off()
pdf("pdfExample.pdf", width = 10, height = 10); p; dev.off()
```

**Comment by esovik** [comment]
``` r
require(ggplot2)

p <- ggplot(data.frame(), aes(x = 1, xend = 2,y  = 1, yend = 2)) +
  geom_curve(size = 4, alpha = 0.2) +
  theme_blank()

png("pngExample.png", width = 1000, height = 1000); p; dev.off()
jpeg("jpgExample.jpg", width = 1000, height = 1000); p; dev.off()
pdf("pdfExample.pdf", width = 10, height = 10); p; dev.off()
```

Yep is reproduced by geom_curve alone. Sorry for having wasted everyone's time.

**Comment by briatte** [comment]
> Sorry for having wasted everyone's time.

No worries, interesting to know this issue exists!
